### ISSUE TITLE
crash at startup in syncTracks()

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast#23]
Something causing crash at startup in syncTracks().
This is probably an initialization timing issue.

It usually happens on the first time 'npm start'.
Subsequent startup will usually work fine.

```
[root@osboxes jbserver]# npm start

> server@0.0.0 start /var/www/html/jbserver
> node app.js

/var/www/html/jbrowse//plugins/JBClient/servermod
error opening /var/www/html/jbrowse//plugins/JBClient/servermod/package.json
/var/www/html/jbrowse//plugins/JBlast/servermod
JBrowse server module found jb-galaxy-blast
symlink exists for jb-galaxy-blast
info: kue job monitor starting
redis server, port 6379
config of Middleware config/http.js for jbrowse
info: starting kueJobMon
debug: init_history
info: galaxy_kue_sync starting
Sails Hook: jb-trackwatch initialized
jbcore initialize
debug: syncTracks()
/var/www/html/jbserver/api/hooks/jb-trackwatch/index.js:209
    JbTrack.find({dataSet:dataSet})
    ^

ReferenceError: JbTrack is not defined
    at syncTracks (/var/www/html/jbserver/api/hooks/jb-trackwatch/index.js:209:5)
    at Timeout._onTimeout (/var/www/html/jbserver/api/hooks/jb-trackwatch/index.js:16:17)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

npm ERR! Linux 3.10.0-327.36.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! server@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.0.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/jbserver/npm-debug.log
[root@osboxes jbserver]# 

```

**Comment by nathandunn** [comment]
@enuggetry  I usually run these in a fixed timer testing the load every 100 ms or so because of this.
